
import express from 'express';
import config from '../config/index';
import Area from '../models/areas';
import ShopCategories from '../models/shopCategories';
let router = express.Router();
import mongoose from "mongoose";

  
router.post(
  "/insert-data",
  async (req, res) => {
    let shopCategories = [
        "Auto Parts",
        "Tires",
        "Companies with Auto Services",
        "Motorcycle and ATV Parts and Gear",
        "Baby Furniture",
        "Baby Gear",
        "Baby Care and Safety",
        "Baby Clothing",
        "Shoes",
        "Jewelry",
        "Watches",
        "Clothing Accessories",
        "Costumes",
        "Kids' Clothing",
        "Women's Clothing",
        "Men's Clothing",
        "Handbags",
        "Uniforms and Scrubs",
        "Teen Clothing",
        "Laptops",
        "Desktop Computers",
        "Computer Monitors",
        "Laptop Bags",
        "Hardware and Peripherals",
        "Computer Networking",
        "Printers and Office Electronics",
        "Tablets",
        "Video Games and Consoles",
        "Cameras and Camcorders",
        "Televisions",
        "MP3 and Media Players",
        "Home Theater",
        "Car Electronics",
        "Electronics Accessories",
        "Gadgets",
        "Cell Phone Accessories",
        "Companies with Cell Phones and Plans",
        "Headphones",
        "Smartwatches",
        "Companies with Tickets",
        "Media",
        "Collectibles",
        "Toys and Games",
        "Crafts and Fabrics",
        "Companies with Discount Clubs",
        "Musical Instruments",
        "Party and Event Supplies",
        "Sheet Music",
        "Specialty Food",
        "Flower Delivery",
        "Personalized Gifts",
        "Stationery and Cards",
        "Companies with Gift Clubs",
        "Photo Gifts and Prints",
        "Gift Cards",
        "Gift Baskets",
        "Construction and Household Materials",
        "Groceries",
        "Food Storage",
        "Religious",
        "Beverages",
        "Special Diet",
        "Meat and Seafood",
        "Cheese",
        "Desserts and Sweets",
        "Packaged Meals and Snacks",
        "Popcorn",
        "Convenience Stores",
        "Novelty Gifts",
        "Cigars",
        "Fruit Gifts",
        "Vaping",
        "Personal Care",
        "Cosmetics",
        "Supplements",
        "Hair Care",
        "Fragrances",
        "Skin Care",
        "Dental Care",
        "Independent Living",
        "Medical Supplies",
        "Men's Grooming",
        "Sexual Wellness",
        "Vision Care",
        "Pet Supplies and Products",
        "Luggage",
        "Furniture",
        "Appliances",
        "Bed and Bath",
        "Home Decor",
        "Tools and Accessories",
        "Storage and Organization",
        "Vacuums and Cleaning Products",
        "Cookware and Cutlery",
        "Tableware",
        "Small Appliances",
        "Plants and Gardening",
        "Pools and Supplies",
        "Blinds",
        "Home Improvement",
        "Companies with Career Services",
        "Office Supplies",
        "Office Furniture",
        "Companies with Payroll",
        "Ink and Toner",
        "Companies with Online Meetings and Communication",
        "Business Cards and Printing",
        "School Supplies",
        "Companies with Marketing and PR",
        "Companies with Small Business Legal Services",
        "Companies with Web Hosting and Tools",
        "Bookkeeping",
        "Checks",
        "Restaurant",
        "Restaurant Supplies",
        "Stock Images and Videos",
        "Companies with Professional Development",
        "Custom Printing",
        "Companies with Financial Services",
        "Companies with Dating",
        "Companies with Personal Legal Services",
        "Companies with Genealogy",
        "Companies with Tutoring and Test Prep",
        "Companies with Sitters and Nannies",
        "Companies with People Search",
        "Companies with Home Services",
        "Companies with Online Weight Loss Plans",
        "Companies with Meal Delivery",
        "Fast Food",
        "Casual Dining",
        "Italian",
        "Steak",
        "Seafood",
        "Breakfast",
        "Mexican",
        "Bar and Grill",
        "Companies with Restaurant Delivery",
        "Tax Preparation",
        "Companies with Online Backup",
        "Maintenance and Utilities",
        "Web Design and Development",
        "Graphics and Photo Editing",
        "Audio and Video Editing",
        "Personal Finance",
        "Productivity",
        "Antivirus and Security",
        "Education",
        "Outdoor Recreation",
        "Sportswear and Gear",
        "Indoor Games and Recreation",
        "Team Apparel and Merchandise",
        "Golf",
        "Team Sports Equipment",
        "Water Sports",
        "Winter Sports",
        "Fitness",
        "Billiards",
        "Companies with Flights",
        "Companies with Hotels",
        "Companies with Car Rental",
        "Companies with Cruises",
        "Companies with Vacation Packages",
        "Companies with Resorts",
        "Companies with Rail and Car Services",
        "Companies with Travel Services",
        "Companies with Vacation Homes"
      ]
    try {
        shopCategories.forEach(async (ar) => {
            let newData = await new ShopCategories({
                name: ar,
                isActive: true
            });
            await newData.save();
        });
        return res.json({
            result: "ok"
        });
    } catch (err) {
        return res.status(500).send(err);
    }
  }
)

export default router;
